import Head from 'next/head';
import Image from 'next/image';
import { Board } from '../components/board/Board';
import { HeaderComp } from '../components/header/HeaderComp';
import { IssuesSection } from '../components/sidebar/IssuesSection';
import { TagsSection } from '../components/sidebar/TagsSection';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Kanban</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-screen">
        <div className="w-64 px-8 py-4 bg-gray-100 border-r">
          <img className="w-14 h-14" src="./img/logo.png" alt="logo" />
          <nav className="mt-8">
            <IssuesSection />
            <TagsSection />
            <button className="flex items-center text-sm font-medium text-gray-500">
              <svg
                className="w-5 h-5 -ml-1 text-gray-500"
                xmlns="http://www.w3.org/2000/svg"
                className="w-6 h-6"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M12 6v6m0 0v6m0-6h6m-6 0H6"
                />
              </svg>
              <span className="ml-1">New Project</span>
            </button>
          </nav>
        </div>
        <div className="flex-1 bg-white">
          <HeaderComp />
          <Board />
        </div>
      </div>
    </div>
  );
}
